# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020f9b30d1d1ebfb9551699e325bca3e0c84a2da47ace52ededd1bd0dac754af9453512aba40a3a80e36b36c49640285a217afcb9e94d36f1182bea3f32881f6

test:
  secret_key_base: 8f0fbcf0056fdaec0e5e52c180e674353cb1a739b793de9ddcbb016734013329407a3b8e8314079b35a1a3c9ac72a63d559dae288e66816f4a28a6b7e7c2d554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
